services:
  # Main production database
  db:
    image: postgres:15
    restart: always
    container_name: leaderboard-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: leaderboarddb
    ports:
      - "5434:5432" # Avoid local conflicts
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

  # Test database (only runs with `--profile test`)
  test-db:
    image: postgres:15
    container_name: leaderboard-test-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: leaderboard_test
    ports:
      - "5435:5432"
    volumes:
      - test_pgdata:/var/lib/postgresql/data
    profiles:
      - test

  # Web application (Next.js)
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/leaderboarddb
      - NODE_ENV=production
      - SEED_SECRET=demo123
    command: >
      sh -c "
        npx prisma generate &&
        npx prisma db push &&
        npx prisma db seed &&
        npm run start
      "
    depends_on:
      - db

  # Jest test runner (only runs with `--profile test`)
  test-runner:
    build:
      context: .
    command: >
      sh -c "
        npx prisma generate &&
        npx prisma db push &&
        npx prisma db seed &&
        npm run test
      "
    depends_on:
      - test-db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@test-db:5432/leaderboard_test
      - NODE_ENV=test
    volumes:
      - .:/app
    profiles:
      - test

volumes:
  pgdata:
  test_pgdata:
